on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/assets/*'
          remote_path: '/var/www/html/assets' #make sure dir exist
          args: '-o ConnectTimeout=5'
